<a href="https://colab.research.google.com/github/PieBerlin/AI-Projects/blob/main/MushroomClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [71]:
#getting dataset
df=pd.read_csv('/content/mushrooms.csv')

In [72]:
df.shape

(8124, 23)

In [73]:
df.head()

  class cap-shape cap-surface  ... spore-print-color population habitat
0     p         x           s  ...                 k          s       u
1     e         x           s  ...                 n          n       g
2     e         b           s  ...                 n          n       m
3     p         x           y  ...                 k          s       u
4     e         x           s  ...                 n          a       g

[5 rows x 23 columns]

In [74]:

le=LabelEncoder()

In [75]:
df_encoded=df.apply(le.fit_transform,axis=0)

In [76]:
df_encoded.head()

   class  cap-shape  cap-surface  ...  spore-print-color  population  habitat
0      1          5            2  ...                  2           3        5
1      0          5            2  ...                  3           2        1
2      0          0            2  ...                  3           2        3
3      1          5            3  ...                  2           3        5
4      0          5            2  ...                  3           0        1

[5 rows x 23 columns]

In [77]:
df=df_encoded.values

In [78]:
x=df[:,1:]
x

array([[5, 2, 4, ..., 2, 3, 5],
       [5, 2, 9, ..., 3, 2, 1],
       [0, 2, 8, ..., 3, 2, 3],
       ...,
       [2, 2, 4, ..., 0, 1, 2],
       [3, 3, 4, ..., 7, 4, 2],
       [5, 2, 4, ..., 4, 1, 2]])

In [79]:
y=df[:,0]

In [80]:
y

array([1, 0, 0, ..., 0, 1, 0])

In [81]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

# posterior probability
##likelyhood propab
## prior propab

In [82]:
#prior propability
def prior_propab(y_train,label):
  m=y_train.shape[0]
  s=np.sum(y_train==label)
  return m/s

In [87]:
#likely hood
def cond_propab(x_train,y_train,feature_col,feature_val,label):
  x_filtered=x_train[y_train==label]
  num=np.sum(x_filtered[:,feature_col]==feature_val)
  denom=x_filtered.shape[0]
  return float(num/denom)

In [94]:
def predict(x_train,y_train,x_test):
  classes=np.unique(y_train)
  n_features=x_train.shape[1]
  posterior_propab=[]

  for label in classes:
    likelyhood=1.0
    for fea in range(n_features):
      cond=cond_propab(x_train,y_train,fea,x_test[fea],label)
      likelyhood=likelyhood*cond
    prior=prior_propab(y_train,label)
    post=likelyhood*prior
  posterior_propab.append(post)
  pred=np.argmax(posterior_propab)
  return pred

In [97]:
def accuracy(x_train,y_train,x_test,y_test):
  pred=[]
  for i in range(x_test.shape[0]):
    p=predict(x_train,y_train,x_test[i])
    pred.append(p)
  y_pred=np.array(pred)
  acc=np.sum(y_pred==y_test)/y_pred.shape[0]
  return acc

In [98]:
result=accuracy(x_train,y_train,x_test,y_test)
result

np.float64(0.5187692307692308)