## Importing the dependencies

In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 
from sklearn.linear_model import LogisticRegression

In [3]:
# load dataset
credit_card_data = pd.read_csv('creditcard.csv')

In [4]:
credit_card_data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [5]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [6]:
## class
#  1 = transaction is fraud
#  0 = transaction is legit

In [7]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [10]:
# we have no missing values

In [11]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

#### Distibution of legit transaction  and fradulent transaction

In [13]:
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [14]:
## we have unbalanced dataset

### separating the data for analysis

In [15]:
legit  = credit_card_data[credit_card_data.Class == 0]

In [16]:
fraud  = credit_card_data[credit_card_data.Class == 1]

In [17]:
fraud.shape

(492, 31)

In [19]:
legit.shape

(284315, 31)

In [21]:
## statistical measures 
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [22]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [24]:
## Compare the values for both transaction
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

#### Under sampling

##### build a sample dataset containig simillar distribution of normal transaction and fradulent transactions

In [25]:
#fraudulent transactions  was 492

In [26]:
legit_sample = legit.sample(n = 492)

## concatinating two dataframes

In [27]:
new_dataset = pd.concat([legit_sample, fraud],axis = 0 )

In [28]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279506,168914.0,0.036777,0.825349,0.284599,-0.588419,0.401272,-1.056775,0.956856,-0.153195,0.028991,...,-0.261221,-0.587733,0.078210,-0.033288,-0.521544,0.145114,0.247741,0.095709,1.29,0
29196,35359.0,0.579988,-1.757091,-0.852842,-0.639489,0.975834,4.000225,-0.762122,0.961973,1.033784,...,-0.071863,-0.906174,-0.268598,1.095571,0.164687,0.919930,-0.098631,0.069443,364.08,0
43233,41426.0,-4.882172,3.998537,0.438130,-2.687614,-0.578040,-1.045689,1.317277,-0.734027,4.655127,...,-0.981426,-0.352156,-0.031267,0.465727,0.402274,0.530162,0.613003,-0.767686,0.68,0
241522,151060.0,2.048629,-0.367489,-2.544065,-0.728472,2.387380,3.318407,-0.477692,0.791276,0.403246,...,-0.292703,-0.835377,0.380780,0.698235,-0.265199,0.219159,-0.052337,-0.066750,1.98,0
87464,61695.0,1.001840,-0.648162,1.025029,0.266148,-1.059527,0.125117,-0.587329,0.146816,1.128583,...,-0.149180,-0.309722,0.028966,0.176752,0.045927,0.961239,-0.030833,0.026933,94.84,0

In [29]:
new_dataset

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279506,168914.0,0.036777,0.825349,0.284599,-0.588419,0.401272,-1.056775,0.956856,-0.153195,0.028991,...,-0.261221,-0.587733,0.078210,-0.033288,-0.521544,0.145114,0.247741,0.095709,1.29,0
29196,35359.0,0.579988,-1.757091,-0.852842,-0.639489,0.975834,4.000225,-0.762122,0.961973,1.033784,...,-0.071863,-0.906174,-0.268598,1.095571,0.164687,0.919930,-0.098631,0.069443,364.08,0
43233,41426.0,-4.882172,3.998537,0.438130,-2.687614,-0.578040,-1.045689,1.317277,-0.734027,4.655127,...,-0.981426,-0.352156,-0.031267,0.465727,0.402274,0.530162,0.613003,-0.767686,0.68,0
241522,151060.0,2.048629,-0.367489,-2.544065,-0.728472,2.387380,3.318407,-0.477692,0.791276,0.403246,...,-0.292703,-0.835377,0.380780,0.698235,-0.265199,0.219159,-0.052337,-0.066750,1.98,0
87464,61695.0,1.001840,-0.648162,1.025029,0.266148,-1.059527,0.125117,-0.587329,0.146816,1.128583,...,-0.149180,-0.309722,0.028966,0.176752,0.045927,0.961239,-0.030833,0.026933,94.84,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [30]:
new_dataset.Class.value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [31]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,97674.995935,-0.158416,-0.029179,-0.030121,0.024414,0.105466,-0.077935,0.049973,0.007270,-0.000432,...,-0.052505,-0.039526,0.001385,-0.009468,0.002487,0.036207,0.010195,-0.000929,-0.024285,72.875142
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

## splitting dtaset into features an target

In [32]:
Y = new_dataset['Class']
X = new_dataset.drop(columns ='Class',axis =1 )

In [33]:
X

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
279506,168914.0,0.036777,0.825349,0.284599,-0.588419,0.401272,-1.056775,0.956856,-0.153195,0.028991,...,-0.079919,-0.261221,-0.587733,0.078210,-0.033288,-0.521544,0.145114,0.247741,0.095709,1.29
29196,35359.0,0.579988,-1.757091,-0.852842,-0.639489,0.975834,4.000225,-0.762122,0.961973,1.033784,...,0.769400,-0.071863,-0.906174,-0.268598,1.095571,0.164687,0.919930,-0.098631,0.069443,364.08
43233,41426.0,-4.882172,3.998537,0.438130,-2.687614,-0.578040,-1.045689,1.317277,-0.734027,4.655127,...,3.025142,-0.981426,-0.352156,-0.031267,0.465727,0.402274,0.530162,0.613003,-0.767686,0.68
241522,151060.0,2.048629,-0.367489,-2.544065,-0.728472,2.387380,3.318407,-0.477692,0.791276,0.403246,...,-0.152758,-0.292703,-0.835377,0.380780,0.698235,-0.265199,0.219159,-0.052337,-0.066750,1.98
87464,61695.0,1.001840,-0.648162,1.025029,0.266148,-1.059527,0.125117,-0.587329,0.146816,1.128583,...,0.093074,-0.149180,-0.309722,0.028966,0.176752,0.045927,0.961239,-0.030833,0.026933,94.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,1.252967,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.226138,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.247968,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.306271,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.017652,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53

In [34]:
Y

279506    0
29196     0
43233     0
241522    0
87464     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

### Split features into training and test data

In [35]:
X_train, X_test , Y_train , Y_test = train_test_split(X, Y,test_size = 0.2, stratify = Y, random_state = 2)

## Model training

In [36]:
model = LogisticRegression()

In [38]:
model.fit(X_train, Y_train)

C:\Users\USER\.conda\envs\ds_env\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

### Predicting with test data

In [43]:
training_data_prediction = model.predict(X_train)
training_data_accuracy_score = accuracy_score(training_data_prediction,Y_train)
print(f'Accuracy Score with Training Data is {training_data_accuracy_score:.2f}')

Accuracy Score with Training Data is 0.95

In [44]:
### Prediction with test data

In [45]:
test_data_prediction = model.predict(X_test)
test_data_accuracy_score = accuracy_score(test_data_prediction,Y_test)
print(f'Accuracy Score with Test Data  is {test_data_accuracy_score:.2f}')

Accuracy Score with Test Data  is 0.93